# -*- coding: utf-8 -*-
"""Copy of HKEX-APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SpXumv0fbF5GnMFiPJwF3ZDtgU0ZwPT
"""

target_start_date = pd.to_datetime('2026-06-02')
target_end_date = pd.to_datetime('2026-06-08')

import requests

url = 'https://www1.hkexnews.hk/ncms/json/eds/appactive_app_sehk_c.json'
response = requests.get(url)

#print(response.status_code)
#print(response.text)

import json
import pandas as pd

json_string = response.text
parsed_data = json.loads(json_string)
df = pd.DataFrame(parsed_data['app'])
#display(df.head(5))

df_clean = df[['d', 'a', 'ls','ps']].rename(columns={
    'd': 'lastpost',
    'a': 'company',
    'ls': 'filingcurrent',
    'ps': 'filingprevious'
})

df_clean['lastpost'] = pd.to_datetime(df_clean['lastpost'], format='%d/%m/%Y')
df_clean['filing']=df_clean['filingcurrent']+df_clean['filingprevious']
df_sorted = df_clean.sort_values(by='lastpost', ascending=False)
df_sorted = df_sorted.reset_index(drop=True)

#display(df_sorted.head(5))

from datetime import datetime

target_nf = '申請版本（第一次呈交）'
link_base = 'https://www.hkexnews.hk/app/'

def get_appfile(data):
    matches = [item for item in data if item.get('nF') == target_nf and item.get('d')]
    if not matches:
        return None, None
    earliest_item = min(matches, key=lambda x: x.get('d'))
    return earliest_item.get('d'), f"{link_base}{earliest_item.get('u1')}"

#data=df_sorted['filing'].iloc[0]
#get_appfile(data)

df_sorted[['appdate', 'appfile']] = df_sorted['filing'].apply(
    lambda x: pd.Series(get_appfile(x))
)
df_sorted['appdate'] = pd.to_datetime(df_sorted['appdate'], format='%d/%m/%Y')
#display(df_sorted.head(10))

# Filter the DataFrame for a date range

filtered_df = df_sorted[
    (df_sorted['appdate'] >= target_start_date) &
    (df_sorted['appdate'] <= target_end_date)
][['company','appdate','appfile']]
df_final=filtered_df.copy()
df_final= df_final.reset_index(drop=True)

display(df_final)